### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by bnbon** [Mansi1/mdi-react-icons#2]
Hi, is this still active? Any plan to support react 18.x and above? Does this library support the mui sx={{}} attributes etc?

Its looking promising for the icons I need if its active, but I cannot install with latest mui version is all.

**Comment by Mansi1** [comment]
Hey sorry to answer so late yes it's an Mui icon you can do everything that you are able on normal icons

**Comment by Mansi1** [comment]
I will fix it by updating dependencies

**Comment by Mansi1** [comment]
Fixed it in the new version, thx
